import time

print("Welcome")
time.sleep(1)
print("My Name is AD")
time.sleep(2)
print("I am going to guess your Phone Number")
time.sleep(2)
guess=int(input("Enter the first 3 digits of the phone number:- "))
print("I am going to Multiply this 3 Digit Number with 40")
time.sleep(3)
print(guess,"× 40", "=", (guess)*40)
first = guess*40
time.sleep(2)
print("I am going to Multiply the result", first ,"with 25")
time.sleep(3)
print(first,"× 25", "=", (first)*25)
second = first*25
time.sleep(2)
print(second)
print("I am going to add your next 3 Digit of your Mobile No with", second)
time.sleep(3)
num2 = int(input("Enter the next three numbers of you number :- "))
time.sleep(1)
print(num2,"+", second, "=", num2+second)
time.sleep(3)
third =num2+ second
print(third,"× 50", "=", (third)*50)
time.sleep(2)
fourth = third*50
print("I am going to Add this", fourth , "with 1")
time.sleep(3)
print(fourth,"+ 1", "=", (fourth)+1)
time.sleep(1)
fifth = fourth+1
print("I am going to Multiply this", fifth , "with 400")
time.sleep(3)
print(fifth,"× 400", "=", (fifth)*400)
time.sleep(2)
six = fifth*400
print("I am going to add your last 4 Digit of your Mobile No with", six)
time.sleep(3)
num3 = int(input("Enter the last 4 Digit numbers of you Mobile No :- "))
time.sleep(3)
print(num3,"+", six, "=", num3+six)
seven = num3+six
time.sleep(3)
print("Again adding last 4 Digit of your Mobile No with",seven )
time.sleep(3)
print(seven,"+", num3, "=", seven+num3)
eight = num3+seven
time.sleep(2)
print("Dividing",eight, "byy 2" )
time.sleep(2)
print(eight,"÷","2", "=", eight/2)
time.sleep(3)
nine = int(eight/2)
print("Subtracting",nine, "by 200" )
time.sleep(3)
print(nine,"-","200", "=", nine-200)
time.sleep(1)
ten = nine-200
time.sleep(2)
print ("Is this your phone number", ten)